# Generated by Django 5.2.12 on 2026-04-08 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_email_verification_token_user_is_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('employee', 'Employee'), ('head_of_school', 'Head of School'), ('head_of_admin', 'Head of Administration'), ('hr', 'HR'), ('head_of_department', 'Head of Department')], max_length=20),
        ),
    ]
