# Generated by Django 5.2.12 on 2026-04-13 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('employee', 'Employee'), ('head_of_school', 'Head of School'), ('head_of_admin', 'Head of Administration'), ('hr', 'HR'), ('head_of_department', 'Head of Department'), ('scheduling_team', 'Scheduling Team')], max_length=20),
        ),
    ]
