# Generated by Django 5.2.12 on 2026-05-13 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('admin', 'Admin'), ('head_of_department', 'Head of Department'), ('head_of_school', 'Head of School'), ('head_of_admin', 'Head of Administration'), ('hr', 'HR'), ('scheduling_team', 'Scheduling Team')], max_length=20),
        ),
    ]
