# Generated by Django 5.2.12 on 2026-05-14 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('admin', 'Admin'), ('head_of_department', 'Head of Department'), ('head_of_school', 'Head of School'), ('head_of_admin', 'Head of Administration'), ('hr', 'HR'), ('scheduling_team', 'Scheduling Team'), ('calendar_access', 'Calendar Access')], max_length=20),
        ),
    ]
