# Generated by Django 5.2.12 on 2026-05-22 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_accountingemail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountingEmail',
        ),
    ]
