# Generated by Django 5.2.12 on 2026-04-07 01:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('vacation_leave', 'Vacation Leave'), ('sick_leave', 'Sick Leave'), ('emergency_leave', 'Emergency Leave'), ('maternity_paternity_leave', 'Maternity / Paternity Leave'), ('bereavement_leave', 'Bereavement Leave'), ('others', 'Other')], max_length=30)),
                ('reason_for_leave', models.TextField()),
                ('start_leave', models.DateField()),
                ('end_leave', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
