# Generated by Django 5.2.12 on 2026-04-07 01:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('vacation_leave', 'Vacation Leave'), ('sick_leave', 'Sick Leave'), ('emergency_leave', 'Emergency Leave'), ('maternity_paternity_leave', 'Maternity / Paternity Leave'), ('bereavement_leave', 'Bereavement Leave'), ('others', 'Other')], max_length=30)),
                ('total_days', models.IntegerField(default=0)),
                ('days_used', models.IntegerField(default=0)),
                ('days_remaining', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
