# Generated by Django 5.2.12 on 2026-04-07 03:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0003_approvaltoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 4, 7, 3, 2, 56, 369130, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leave',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leave',
            name='status',
            field=models.CharField(choices=[('pending_hos', 'Pending Head of School'), ('pending_hoa', 'Pending Head of Administration'), ('pending_hr', 'Pending HR'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending_hos', max_length=20),
        ),
    ]
