# Generated by Django 5.2.12 on 2026-04-08 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0004_leave_created_at_leave_rejection_reason_leave_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='status',
            field=models.CharField(choices=[('pending_hod', 'Pending Head of Department Approval'), ('pending_hos', 'Pending Head of School Approval'), ('pending_hoa', 'Pending Head of Administration Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending_hos', max_length=20),
        ),
    ]
