# Generated by Django 5.2.12 on 2026-04-09 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0005_alter_leave_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='pdf_attachment',
            field=models.FileField(blank=True, null=True, upload_to='leave_pdfs/'),
        ),
    ]
