# Generated by Django 5.2.12 on 2026-04-28 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0007_alter_leave_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavebalance',
            name='carried_over',
            field=models.IntegerField(default=0),
        ),
    ]
