# Generated by Django 5.2.12 on 2026-05-09 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0008_leavebalance_carried_over'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='status',
            field=models.CharField(choices=[('pending_hod', 'Pending Head of Department Approval'), ('pending_hos', 'Pending Head of School Approval'), ('pending_hoa', 'Pending Head of Administration Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending_hod', max_length=20),
        ),
        migrations.AlterField(
            model_name='leave',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
