# Generated by Django 5.2.12 on 2026-05-13 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0009_alter_leave_status_alter_leave_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='half_day',
            field=models.CharField(choices=[('none', 'Full Day'), ('morning', 'Morning only'), ('afternoon', 'Afternoon only')], default='none', max_length=10),
        ),
    ]
