# Generated by Django 5.2.12 on 2026-05-13 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0010_leave_half_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavebalance',
            name='leave_type',
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='carried_over',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='days_remaining',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='days_used',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='total_days',
            field=models.FloatField(default=0),
        ),
    ]
