# Generated by Django 5.2.12 on 2026-05-13 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0011_remove_leavebalance_leave_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavebalance',
            name='leave_type',
            field=models.CharField(choices=[('vacation_leave', 'Vacation Leave'), ('sick_leave', 'Sick Leave'), ('emergency_leave', 'Emergency Leave'), ('maternity_paternity_leave', 'Maternity / Paternity Leave'), ('bereavement_leave', 'Bereavement Leave'), ('others', 'Other')], default='vacation_leave', max_length=30),
            preserve_default=False,
        ),
    ]
