# Generated by Django 5.2.12 on 2026-05-14 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0012_leavebalance_leave_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavebalance',
            name='is_unpaid',
            field=models.BooleanField(default=False),
        ),
    ]
