# Generated by Django 5.2.12 on 2026-05-14 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0013_leavebalance_is_unpaid'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='is_unpaid',
            field=models.BooleanField(default=False),
        ),
    ]
